# Generated by Django 4.0.1 on 2022-02-21 15:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('postalcode', models.CharField(max_length=10)),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('o_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order')),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
